'use strict';
window.addEventListener('error', (event) => {
  const el = document.getElementById('status');
  if (el) el.textContent = 'エラーが発生しました：' + (event.message || '不明なエラー');
});
window.addEventListener('unhandledrejection', (event) => {
  const el = document.getElementById('status');
  if (el) el.textContent = '通信または処理エラー：' + (event.reason?.message || event.reason || '不明なエラー');
});

const API='https://api.scryfall.com';const $=x=>document.getElementById(x);let pool=[],deck=[],recs=[],singleRecs=[];const sleep=x=>new Promise(r=>setTimeout(r,x));
window.addEventListener('error',e=>{const el=document.getElementById('status');if(el)el.textContent='画面エラー：'+(e.message||'不明なエラー');});
const JP={W:'白',U:'青',B:'黒',R:'赤',G:'緑'};function colors(a=[]){return a.length?a.map(x=>JP[x]).join(''):'無色'}function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}function type(c){return [c.type_line,...(c.card_faces||[]).map(x=>x.type_line)].filter(Boolean).join(' // ')}function text(c){return [c.oracle_text,...(c.card_faces||[]).map(x=>x.oracle_text)].filter(Boolean).join('\n').toLowerCase()}function img(c){return c.image_uris?.normal||c.card_faces?.[0]?.image_uris?.normal||''}function unique(a){return [...new Set(a.filter(Boolean))]}
const RX={token_make:/create[s]? (?:one|two|three|a|an|x|that many|\d+)[^\.]{0,80} token|food token|treasure token|clue token|blood token/i,token_payoff:/whenever (?:one or more )?(?:tokens?|artifacts?)|sacrifice (?:a|another) token|tokens? you control get/i,counter_make:/put (?:a|one|two|three|x|that many|\d+)[^\.]{0,40} counters?|proliferate/i,counter_payoff:/if [^\.]{0,50}counter|for each [^\.]{0,30}counter|remove [^\.]{0,30}counter|modified creature/i,grave_fill:/mill |surveil|put the top [^\.]+ into your graveyard|discard a card/i,grave_payoff:/from your graveyard|cards? in your graveyard|descend|delirium|collect evidence|exile [^\.]+ from your graveyard/i,sac_outlet:/sacrifice another|sacrifice a creature|sacrifice an artifact/i,death_payoff:/whenever (?:another )?[^\.]{0,35} dies|creature died|permanent was put into a graveyard/i,draw:/draw (?:a|one|two|three|x|that many|\d+) cards?|investigate/i,removal:/destroy target|exile target|deals? \d+ damage to target|target creature gets -|counter target spell|return target [^\.]+ to its owner's hand/i,ramp:/add \{|search your library for (?:a|up to one) (?:basic )?land|treasure token|additional land/i,protection:/hexproof|indestructible|phasing|protection from|ward \{|return target [^\.]+ you control to its owner's hand/i,finisher:/double strike|trample|can't be blocked|each opponent loses|extra turn|you win the game/i,life_make:/you gain|lifelink/i,life_payoff:/whenever you gain life|if you gained life/i,spell_payoff:/whenever you cast (?:an? )?(?:instant|sorcery|noncreature|spell)|prowess/i,artifact_payoff:/artifacts? you control|whenever an artifact|for each artifact/i,enchant_payoff:/enchantments? you control|whenever an enchantment|constellation/i,land_payoff:/landfall|whenever a land enters|for each land/i,attack_payoff:/whenever [^\.]{0,40} attacks|attacking creature|combat damage to a player/i,blink:/exile [^\.]{0,80} then return|return [^\.]{0,80} to the battlefield/i};
const labels={token_make:'トークン生成',token_payoff:'トークン利用',counter_make:'カウンター付与',counter_payoff:'カウンター利用',grave_fill:'墓地を肥やす',grave_payoff:'墓地利用',sac_outlet:'生け贄手段',death_payoff:'死亡誘発',draw:'ドロー',removal:'除去／妨害',ramp:'マナ加速',protection:'保護',finisher:'勝ち手段',life_make:'ライフゲイン',life_payoff:'ライフゲイン利用',spell_payoff:'呪文誘発',artifact_payoff:'アーティファクト利用',enchant_payoff:'エンチャント利用',land_payoff:'土地誘発',attack_payoff:'攻撃誘発',blink:'明滅'};
const pairs=[['token_make','token_payoff'],['token_make','sac_outlet'],['sac_outlet','death_payoff'],['grave_fill','grave_payoff'],['counter_make','counter_payoff'],['life_make','life_payoff'],['blink','death_payoff'],['ramp','finisher']];
function features(c){let o=text(c),t=type(c).toLowerCase();let roles=Object.keys(RX).filter(k=>RX[k].test(o));let subs=(t.split('—')[1]||'').replace(/\/\//g,' ').split(/\s+/).map(x=>x.replace(/[^a-z]/g,'')).filter(x=>x.length>3);return{roles,subs:unique(subs),o,t,cmc:+c.cmc||0,colors:c.color_identity||[]}}
function parseDeck(s){let side=false,out=[];for(let raw of s.split(/\r?\n/)){let line=raw.trim();if(!line||/^(deck|companion)$/i.test(line))continue;if(/^sideboard$/i.test(line)){side=true;continue}let m=line.match(/^(?:SB:\s*)?(\d+)x?\s+(.+?)(?:\s+\([A-Z0-9]+\)\s+\d+)?$/i);if(!m)m=[null,'1',line];out.push({qty:+m[1],name:m[2].trim(),side})}return out}
function status(s,p){$('status').textContent=s;if(p!=null)$('bar').style.width=p+'%'}
async function fetchPool(){let cached;try{cached=JSON.parse(localStorage.getItem('mtgStdPoolV3')||'null')}catch{}if(cached&&Date.now()-cached.time<1000*60*60*24*3&&cached.cards?.length){pool=cached.cards;finishPool('キャッシュから');return}pool=[];$('loadBtn').disabled=true;let url=API+'/cards/search?order=name&unique=cards&q='+encodeURIComponent('legal:standard game:paper');let n=0;try{while(url){n++;status(`スタンダード全カード取得中：${n}ページ`,Math.min(94,n*5));let r=await fetch(url);if(!r.ok)throw Error('API '+r.status);let j=await r.json();pool.push(...j.data.filter(c=>!c.digital));url=j.has_more?j.next_page:null;await sleep(120)}try{localStorage.setItem('mtgStdPoolV3',JSON.stringify({time:Date.now(),cards:pool}))}catch{}finishPool('オンラインから')}catch(e){status('取得失敗：'+e.message,0);$('loadBtn').disabled=false}}
function finishPool(src){status(`${src}${pool.length.toLocaleString()}種類を読み込みました。`,100);$('loadBtn').disabled=false;$('analyzeBtn').disabled=false;$('singleBtn').disabled=false;$('singleStatus').textContent=`${pool.length.toLocaleString()}種類を使用可能`;populateCardNames();if($('dbStatus')){$('dbStatus').textContent=`${pool.length.toLocaleString()}種類を検索できます。`;renderDatabase();}}
async function named(name){let exact=pool.find(c=>c.name.toLowerCase()===name.toLowerCase());if(exact)return exact;let r=await fetch(API+'/cards/named?fuzzy='+encodeURIComponent(name));return r.ok?r.json():null}
function deckStats(cards){let main=cards.filter(x=>!x.side&&x.card),total=main.reduce((s,x)=>s+x.qty,0),lands=main.filter(x=>type(x.card).includes('Land')).reduce((s,x)=>s+x.qty,0),non=main.filter(x=>!type(x.card).includes('Land')),avg=non.reduce((s,x)=>s+x.qty*(x.card.cmc||0),0)/Math.max(1,non.reduce((s,x)=>s+x.qty,0)),cols=unique(main.flatMap(x=>x.card.color_identity||[])),counts={};for(let x of non)for(let r of features(x.card).roles)counts[r]=(counts[r]||0)+x.qty;let curve=Array(8).fill(0);for(let x of non)curve[Math.min(7,Math.floor(x.card.cmc||0))]+=x.qty;return{main,total,lands,avg,cols,counts,curve}}
function diagnosis(s){let a=[];if(s.total<60)a.push(['bad',`メインが${s.total}枚（60枚未満）`]);else if(s.total>60)a.push(['warn',`メインが${s.total}枚（60枚超）`]);else a.push(['good','メイン60枚']);if(s.lands<20)a.push(['bad',`土地${s.lands}枚：かなり少ない`]);else if(s.lands<23)a.push(['warn',`土地${s.lands}枚：軽量デッキ向け`]);else if(s.lands>28)a.push(['warn',`土地${s.lands}枚：多め`]);else a.push(['good',`土地${s.lands}枚`]);if((s.counts.removal||0)<4)a.push(['bad','除去／妨害が不足']);if((s.counts.draw||0)<3)a.push(['warn','継続的な手札補充が少ない']);if((s.counts.protection||0)<2)a.push(['warn','主力を守る手段が少ない']);if((s.counts.finisher||0)<3&&s.avg>2.5)a.push(['warn','明確な勝ち手段が少ない']);if(s.curve[2]+s.curve[3]<10)a.push(['warn','2～3マナ域が薄い']);return a}
function scoreCard(c,stats,strategy,seedCards){let f=features(c),score=0,why=[];let outside=f.colors.filter(x=>!stats.cols.includes(x));if(outside.length){score-=35*outside.length}else{score+=9;why.push('デッキ色に適合')}let deckRoles=stats.counts;for(let [maker,payoff] of pairs){if((deckRoles[maker]||0)>0&&f.roles.includes(payoff)){score+=14;why.push(`${labels[maker]}を${labels[payoff]}で活用`)}if((deckRoles[payoff]||0)>0&&f.roles.includes(maker)){score+=12;why.push(`${labels[payoff]}を支える${labels[maker]}`)}}let needs={removal:4,draw:4,ramp:3,protection:2,finisher:3};for(let [r,n] of Object.entries(needs))if((deckRoles[r]||0)<n&&f.roles.includes(r)){score+=13;why.push(`不足している${labels[r]}を補完`)}let avg=stats.avg||3,d=Math.abs(f.cmc-avg);score+=Math.max(0,7-d*2);let band=Math.min(7,Math.floor(f.cmc));if(stats.curve[band]<4){score+=6;why.push(`${band===7?'7+':band}マナ域を補完`)}else if(stats.curve[band]>10)score-=4;let deckSubs=seedCards.flatMap(x=>features(x.card).subs);let shared=f.subs.filter(x=>deckSubs.includes(x));if(shared.length){score+=strategy==='tribal'?18:9;why.push(`${shared[0]}タイプ連携`)}if(strategy==='engine'&&why.some(x=>x.includes('活用')||x.includes('支える')))score+=8;if(strategy==='support'&&f.roles.some(x=>['removal','draw','ramp','protection'].includes(x)))score+=6;if(strategy==='curve'&&stats.curve[band]<4)score+=7;if(type(c).includes('Land')&&stats.lands>=25)score-=8;score+=Math.min(5,f.roles.length);return{card:c,score:Math.round(score*10)/10,why:unique(why).slice(0,6),f}}
async function analyze(){if(!pool.length){status('先にカードデータを取得します。',3);await fetchPool();if(!pool.length)return;}let parsed=parseDeck($('deckInput').value);if(!parsed.length){status('デッキを入力してください。');return}$('analyzeBtn').disabled=true;deck=[];for(let i=0;i<parsed.length;i++){status(`カード特定中 ${i+1}/${parsed.length}`,10+55*i/parsed.length);let c=await named(parsed[i].name);if(c)deck.push({...parsed[i],card:c});else deck.push({...parsed[i],card:null});await sleep(80)}let resolved=deck.filter(x=>x.card),stats=deckStats(deck);renderStats(stats,parsed.length,resolved.length);let present=new Set(resolved.map(x=>x.card.name));recs=pool.filter(c=>!present.has(c.name)).map(c=>scoreCard(c,stats,$('strategy').value,resolved.filter(x=>!x.side))).filter(x=>x.score>8).sort((a,b)=>b.score-a.score);status(`${resolved.length}/${parsed.length}種類を特定し、${recs.length.toLocaleString()}候補を採点しました。`,100);renderResults();$('analyzeBtn').disabled=false}
function renderStats(s,all,res){$('mCards').textContent=s.total;$('mLands').textContent=s.lands;$('mColors').textContent=colors(s.cols);$('mAvg').textContent=s.avg.toFixed(2);$('mResolved').textContent=Math.round(res/Math.max(1,all)*100)+'%';let ds=diagnosis(s),base=100-ds.filter(x=>x[0]==='bad').length*18-ds.filter(x=>x[0]==='warn').length*7;$('mScore').textContent=Math.max(0,base);$('diagnostics').innerHTML=ds.map(x=>`<span class="tag ${x[0]}">${esc(x[1])}</span>`).join('');let max=Math.max(1,...s.curve);$('curve').innerHTML=s.curve.map((v,i)=>`<div class="manaCol"><div class="manaBar" style="height:${Math.max(2,95*v/max)}px"></div><small>${i===7?'7+':i}<br>${v}</small></div>`).join('');let roles=Object.entries(s.counts).sort((a,b)=>b[1]-a[1]);$('roles').innerHTML=roles.length?roles.map(([r,n])=>`<div class="deckcard"><span class="qty">${n}</span><span>${labels[r]||r}</span><span class="tiny">枚</span></div>`).join(''):'<span class="notice">役割を検出できませんでした。</span>';$('resolvedDeck').innerHTML=deck.map(x=>`<div>${x.qty} ${esc(x.card?.name||x.name)} ${x.card?'':'<span class="tag bad">未特定</span>'}</div>`).join('')}
function renderResults(){let q=$('search').value.toLowerCase(),tf=$('typeFilter').value,rf=$('roleFilter').value,cf=$('colorFilter').value,lim=+$('recLimit').value;let arr=recs.filter(x=>(!q||(x.card.name+' '+type(x.card)+' '+text(x.card)).toLowerCase().includes(q))&&(!tf||type(x.card).includes(tf))&&(!rf||x.f.roles.includes(rf))&&(!cf||(cf==='C'?!x.f.colors.length:x.f.colors.includes(cf)))).slice(0,lim);$('results').innerHTML=arr.length?arr.map(x=>cardHTML(x)).join(''):'<div class="empty">条件に合う候補がありません。</div>'}
function cardHTML(x){return `<article class="result"><div>${img(x.card)?`<img loading="lazy" src="${img(x.card)}" alt="${esc(x.card.name)}">`:''}</div><div><h3>${esc(x.card.name)}</h3><div class="meta">${esc(type(x.card))} ・ MV ${x.card.cmc||0} ・ ${colors(x.f.colors)}</div><div class="tags">${x.why.map(w=>`<span class="tag good">${esc(w)}</span>`).join('')}${x.f.roles.slice(0,4).map(r=>`<span class="tag">${labels[r]||r}</span>`).join('')}</div><div class="oracle">${esc(x.card.oracle_text||x.card.card_faces?.map(f=>f.oracle_text).filter(Boolean).join('\n')||'')}</div></div><div><div class="score">${x.score}</div><div class="tiny">適合点</div></div></article>`}
async function singleAnalyze(){if(!pool.length){$('singleStatus').textContent='先にカードデータを取得します。';await fetchPool();if(!pool.length)return;}let name=$('singleName').value.trim();if(!name)return;let c=await named(name);if(!c){$('singleStatus').textContent='カードを特定できませんでした。';return}let fake=[{qty:4,side:false,card:c}],stats=deckStats(fake);singleRecs=pool.filter(x=>x.name!==c.name).map(x=>scoreCard(x,stats,'engine',fake)).sort((a,b)=>b.score-a.score).slice(0,40);$('singleSeed').innerHTML=`<div class="mini"><h3>${esc(c.name)}</h3><div class="tags">${features(c).roles.map(r=>`<span class="tag">${labels[r]||r}</span>`).join('')}</div></div>`;$('singleResults').innerHTML=singleRecs.map(cardHTML).join('');$('singleStatus').textContent='相性候補を表示しました。'}


function populateCardNames(){
  const dl=$('cardNames');
  if(!dl||!pool.length)return;
  dl.innerHTML=pool.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(c=>`<option value="${esc(c.name)}"></option>`).join('');
}
function cardSearchText(c){return `${c.name} ${type(c)} ${text(c)} ${(c.keywords||[]).join(' ')}`.toLowerCase()}
function renderDatabase(){
  if(!pool.length){$('dbResults').innerHTML='<div class="empty">「カードデータを準備」を押してください。</div>';$('dbSummary').textContent='0件';return;}
  const q=$('dbQuery').value.trim().toLowerCase();
  const tf=$('dbType').value,rf=$('dbRole').value,cf=$('dbColor').value,mv=$('dbMv').value,sort=$('dbSort').value;
  let arr=pool.filter(c=>{
    const f=features(c),cm=Math.floor(+c.cmc||0);
    return (!q||cardSearchText(c).includes(q))&&(!tf||type(c).includes(tf))&&(!rf||f.roles.includes(rf))&&(!cf||(cf==='C'?!f.colors.length:f.colors.includes(cf)))&&(!mv||(mv==='7'?cm>=7:cm===+mv));
  });
  if(sort==='mv')arr.sort((a,b)=>(a.cmc||0)-(b.cmc||0)||a.name.localeCompare(b.name));
  else if(sort==='new')arr.sort((a,b)=>(b.released_at||'').localeCompare(a.released_at||'')||a.name.localeCompare(b.name));
  else arr.sort((a,b)=>a.name.localeCompare(b.name));
  $('dbSummary').textContent=`${arr.length.toLocaleString()}件中、先頭${Math.min(80,arr.length)}件を表示`;
  $('dbResults').innerHTML=arr.length?arr.slice(0,80).map(databaseCardHTML).join(''):'<div class="empty">条件に合うカードがありません。</div>';
}
function databaseCardHTML(c){
  const f=features(c),oracle=c.oracle_text||c.card_faces?.map(x=>x.oracle_text).filter(Boolean).join('\n')||'';
  return `<article class="galleryCard">${img(c)?`<img loading="lazy" src="${img(c)}" alt="${esc(c.name)}">`:''}<div class="galleryBody"><h3>${esc(c.name)}</h3><div class="meta">${esc(type(c))}<br>MV ${c.cmc||0} ・ ${colors(f.colors)}</div><div class="tags">${f.roles.slice(0,3).map(r=>`<span class="tag">${labels[r]||r}</span>`).join('')}</div><div class="galleryText">${esc(oracle)}</div><div class="galleryActions"><button class="smallBtn primary" data-synergy="${esc(c.name)}">相性を見る</button><button class="smallBtn" data-deckadd="${esc(c.name)}">デッキへ追加</button></div></div></article>`;
}
function prepareDatabase(){
  if(!pool.length)return fetchPool();
  populateCardNames();renderDatabase();$('dbStatus').textContent=`${pool.length.toLocaleString()}種類を検索できます。`;
}
function addCardToDeck(name){
  const ta=$('deckInput'),current=ta.value.trim();
  ta.value=(current?current+'\n':'Deck\n')+'1 '+name;
  document.querySelector('[data-view="analyzer"]').click();
  status(`${name} をデッキ入力へ追加しました。`);
}

function saves(){try{return JSON.parse(localStorage.getItem('mtgSavedDecks')||'[]')}catch{return[]}}function renderSaves(){let a=saves();$('savedDecks').innerHTML=a.length?a.map((x,i)=>`<div class="savedItem"><div><b>${esc(x.name)}</b><div class="tiny">${new Date(x.time).toLocaleString('ja-JP')}</div></div><div><button class="btn ghost" onclick="loadSave(${i})">開く</button> <button class="btn ghost" onclick="delSave(${i})">削除</button></div></div>`).join(''):'<div class="empty">保存デッキはありません。</div>'}window.loadSave=i=>{let x=saves()[i];$('deckInput').value=x.text;document.querySelector('[data-view="analyzer"]').click()};window.delSave=i=>{let a=saves();a.splice(i,1);localStorage.setItem('mtgSavedDecks',JSON.stringify(a));renderSaves()};
$('saveBtn').onclick=()=>{let text=$('deckInput').value.trim();if(!text)return;let name=prompt('保存名','マイデッキ');if(!name)return;let a=saves();a.unshift({name,text,time:Date.now()});localStorage.setItem('mtgSavedDecks',JSON.stringify(a.slice(0,30)));renderSaves()};
$('sampleBtn').onclick=()=>{$('deckInput').value='Deck\n4 Llanowar Elves\n4 Mossborn Hydra\n4 Innkeeper\'s Talent\n4 Snakeskin Veil\n4 Bushwhack\n4 Pawpatch Formation\n4 Bristly Bill, Spine Sower\n4 Railway Brawler\n2 Archdruid\'s Charm\n2 Nissa, Ascended Animist\n24 Forest'};
$('loadBtn').onclick=fetchPool;$('analyzeBtn').onclick=analyze;$('singleBtn').onclick=singleAnalyze;$('dbLoadBtn').onclick=prepareDatabase;['dbQuery','dbType','dbRole','dbColor','dbMv','dbSort'].forEach(id=>$(id).addEventListener('input',renderDatabase));$('dbResults').addEventListener('click',e=>{const s=e.target.closest('[data-synergy]'),d=e.target.closest('[data-deckadd]');if(s){$('singleName').value=s.dataset.synergy;document.querySelector('[data-view="single"]').click();singleAnalyze();}if(d)addCardToDeck(d.dataset.deckadd);});['search','typeFilter','roleFilter','colorFilter','recLimit'].forEach(id=>$(id).addEventListener('input',renderResults));document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('on'));document.querySelectorAll('.view').forEach(x=>x.classList.remove('on'));b.classList.add('on');$(b.dataset.view).classList.add('on');if(b.dataset.view==='library')renderSaves()});renderSaves();

try{const cached=JSON.parse(localStorage.getItem('mtgStdPoolV3')||'null');if(cached?.cards?.length){pool=cached.cards;populateCardNames();$('dbStatus').textContent=`キャッシュ済み ${pool.length.toLocaleString()}種類`;renderDatabase();}}catch{}
setTimeout(()=>{const el=$('status');if(el&&!pool.length)el.textContent='JavaScript動作確認済み。デッキを入力して「デッキを分析」を押してください。';},100);